In [34]:
import pandas as pd
import numpy as np

In [35]:
# Create empty DataFrame
columns = [
    "Prototype ID",
    "Factor Varied",
    "Factor Level",
    "Pressure (kPa)",
    "Force (N)",
    "Extension (mm)",
    "Radial Expansion (mm)",
    "Test Notes/Observations"
]

df = pd.DataFrame(columns=columns)

# Display the empty table
df

Empty DataFrame
Columns: [Prototype ID, Factor Varied, Factor Level, Pressure (kPa), Force (N), Extension (mm), Radial Expansion (mm), Test Notes/Observations]
Index: []

In [36]:
# add data to the DataFrame
def add_data(
    dataframe,
    prototype_id,
    factor_varied,
    factor_level,
    pressure,
    force,
    extension,
    radial_expansion,
    notes
):
    """
    Appends a single row of experimental data to the DataFrame.
    """
    new_row = {
        "Prototype ID": prototype_id,
        "Factor Varied": factor_varied,
        "Factor Level": factor_level,
        "Pressure (kPa)": pressure,
        "Force (N)": force,
        "Extension (mm)": extension,
        "Radial Expansion (mm)": radial_expansion,
        "Test Notes/Observations": notes
    }
    
    # Append the new row
    # Note: In pandas 1.4+, 'append()' is deprecated. We use concat for safety.
    dataframe = pd.concat([dataframe, pd.DataFrame([new_row])], ignore_index=True)
    return dataframe

In [37]:
# Define parameters of variance
p1 = "Thickness [mm]"
p2 = "Amplitude [mm]"
p3 = "Period"
p4 = "CP2 x-y Displacement"
p5 = "CP1 & CP2 x-y Displacement"
p6 = "CP1 & CP2 Weighting"

# No. of Curves
n_curves = 5

# Pressure
pressure = 20

## Thickness Variation

In [38]:
# Prototype_ID
thickness1 = "A1"
thickness2 = "A2"
thickness3 = "A3"

# Thickness
value1 = 0.5
value2 = 1.0
value3 = 2.0

# End-Effector Force
force1 = 0.0
force2 = 0.0
force3 = 0.0

# Extension
extension1 = 0.0
extension2 = 0.0
extension3 = 0.0

# Radial Expansion
radial_expansion1 = 0.0
radial_expansion2 = 0.0
radial_expansion3 = 0.0

# Test Notes
notes1 = "Test Note 1"
notes2 = "Test Note 2"
notes3 = "Test Note 3"

# prototype_id, factor_varied, factor_level, pressure, force, extension, radial_expansion, notes
thickness_entries = [
    (thickness1, p1, value1, pressure, force1, extension1, radial_expansion1, notes1),
    (thickness2, p1, value2, pressure, force2, extension2, radial_expansion2, notes2),
    (thickness3, p1, value3, pressure, force3, extension3, radial_expansion3, notes3)
]

## Amplitude

In [39]:
# Prototype_ID
amplitude1 = "B1"
amplitude2 = "B2"
amplitude3 = "B3"

# Thickness
value1 = 0.5
value2 = 1.0
value3 = 2.0

# End-Effector Force
force1 = 0.0
force2 = 0.0
force3 = 0.0

# Extension
extension1 = 0.0
extension2 = 0.0
extension3 = 0.0

# Radial Expansion
radial_expansion1 = 0.0
radial_expansion2 = 0.0
radial_expansion3 = 0.0

# Test Notes
notes1 = "Test Note 1"
notes2 = "Test Note 2"
notes3 = "Test Note 3"

# prototype_id, factor_varied, factor_level, pressure, force, extension, radial_expansion, notes
amplitude_entries = [
    (amplitude1, p2, value1, pressure, force1, extension1, radial_expansion1, notes1),
    (amplitude2, p2, value2, pressure, force2, extension2, radial_expansion2, notes2),
    (amplitude3, p2, value3, pressure, force3, extension3, radial_expansion3, notes3)
]

In [40]:
# Define the data entries
data_entries = [
    thickness_entries,
    amplitude_entries
]
# Loop through each entry and add to the DataFrame
for entries in data_entries:
    for entry in entries:
        df = add_data(df, *entry)

# Display the updated table
df

/var/folders/hh/225ky0gd1ybf9sxx9g5y4m480000gn/T/ipykernel_4912/3523708529.py:29: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataframe = pd.concat([dataframe, pd.DataFrame([new_row])], ignore_index=True)

,Prototype ID,Factor Varied,Factor Level,Pressure (kPa),Force (N),Extension (mm),Radial Expansion (mm),Test Notes/Observations
0,A1,Thickness,0.5,20,0.0,0.0,0.0,Test Note 1
1,A2,Thickness,1.0,20,0.0,0.0,0.0,Test Note 2
2,A3,Thickness,2.0,20,0.0,0.0,0.0,Test Note 3
3,B1,Amplitude,0.5,20,0.0,0.0,0.0,Test Note 1
4,B2,Amplitude,1.0,20,0.0,0.0,0.0,Test Note 2
5,B3,Amplitude,2.0,20,0.0,0.0,0.0,Test Note 3

### **Export**

In [42]:
df.to_csv("experimental_data.csv", index=False)